config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   resources :users, only: [:index] # ユーザー一覧のルートを追加
#   resources :chat_rooms, only: [:index, :show, :new, :create] do
#     resources :private_messages, only: [:create]
#   end
#
#   # Direct message routes
#   get 'direct_message', to: 'direct_messages#show', as: 'direct_message'
#   post 'direct_message', to: 'direct_messages#create'
#
#   root "chat_rooms#index"
# end
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index] # ユーザー一覧のルートを追加

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy] do
    resources :private_messages, only: [:create]
  end

  # Direct message routes
  get 'direct_messages', to: 'direct_messages#index', as: 'direct_messages'
  get 'direct_message', to: 'direct_messages#show', as: 'direct_message'
  post 'direct_message', to: 'direct_messages#create'

  root "chat_rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users, dependent: :destroy
  has_many :private_messages, dependent: :destroy
  has_many :users, through: :chat_room_users
  validates :name, presence: true # 一意性のバリデーションを削除

  # validates :name, presence: true, uniqueness: true
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :chat_room_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :content, presence: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :chat_room, optional: true

  validates :content, presence: true

  def user
    sender
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Deviseのモジュール
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # チャットルームとの関連付け
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chat_room, only: [:show, :destroy]

  def index
    @chat_rooms = current_user.chat_rooms
  end

  def show
    @private_message = PrivateMessage.new
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    user_ids = params[:chat_room][:user_ids].reject(&:blank?) # 選択されたユーザーIDを取得し、空のIDを除去

    if user_ids.size == 1
      # 一対一のチャットの場合、チャットルームを作成せずに個別チャットを開始
      chat_partner = User.find(user_ids.first)
      # ここに一対一のチャット処理を追加（例: メッセージページにリダイレクト）
      redirect_to direct_message_path(chat_partner_id: chat_partner.id)
    else
      # 複数ユーザーの場合、チャットルームを作成
      @chat_room = ChatRoom.new(chat_room_params)
      if @chat_room.save
        @chat_room.chat_room_users.create!(user: current_user)
        user_ids.each do |user_id|
          @chat_room.chat_room_users.create!(user_id: user_id) rescue nil
        end
        redirect_to @chat_room
      else
        render :new
      end
    end
  end

  def destroy
    @chat_room.destroy
    redirect_to chat_rooms_path, notice: 'Chat room was successfully deleted.'
  end

  private

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def chat_room_params
    params.require(:chat_room).permit(:name, user_ids: [])
  end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @chat_partner = User.find(params[:chat_partner_id])
    @private_message = PrivateMessage.new
    @private_messages = PrivateMessage.where(sender: current_user, receiver: @chat_partner)
                                      .or(PrivateMessage.where(sender: @chat_partner, receiver: current_user))
                                      .order(:created_at)
  end

  def create
    @chat_partner = User.find(params[:chat_partner_id])
    @private_message = PrivateMessage.new(private_message_params)
    @private_message.sender = current_user
    @private_message.receiver = @chat_partner
    @private_message.user_id = current_user.id

    if @private_message.save
      redirect_to direct_message_path(chat_partner_id: @chat_partner.id)
    else
      @private_messages = PrivateMessage.where(sender: current_user, receiver: @chat_partner)
                                        .or(PrivateMessage.where(sender: @chat_partner, receiver: current_user))
                                        .order(:created_at)
      render :show
    end
  end

  private

  def private_message_params
    params.require(:private_message).permit(:content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message = @chat_room.messages.build(message_params.merge(user: current_user))

    if @message.save
      ActionCable.server.broadcast "chat_room_#{@chat_room.id}_channel", { message: render_message(@message) }
      head :ok
    else
      render 'chat_rooms/show'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'messages/message', locals: { message: message })
  end
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @private_message = @chat_room.private_messages.build(private_message_params)
    @private_message.sender = current_user
    @private_message.receiver = @chat_room.users.where.not(id: current_user.id).first
    @private_message.user_id = current_user.id

    if @private_message.save
      redirect_to @chat_room
    else
      render 'chat_rooms/show'
    end
  end

  private

  def private_message_params
    params.require(:private_message).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<h1>Chat Rooms</h1>

<ul>
  <% @chat_rooms.each do |chat_room| %>
    <li>
      <%= link_to chat_room.name, chat_room %>
      <%= link_to 'Delete', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Chat Room', new_chat_room_path %>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= form_with(model: @chat_room, local: true) do |form| %>
  <% if @chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
        <% @chat_room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_ids, "Chat Partners" %>
    <%= form.collection_select :user_ids, User.all, :id, :email, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.name %></h1>

<div id="messages">
  <%= render @chat_room.private_messages %>
</div>

<%= form_with(model: [@chat_room, PrivateMessage.new], local: true, remote: true) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Send" %>
  </div>
<% end %>


<!--<h2>Messages</h2>-->
<!--<ul>-->
  <%#= render @chat_room.private_messages %>
<!--</ul>-->

<%= link_to 'Back to Chat Rooms', chat_rooms_path %>
<%= link_to 'Delete Chat Room', @chat_room, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/direct_messages/index.html.erb
<h1>Direct Messages</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, direct_message_path(chat_partner_id: user.id) %>
    </li>
  <% end %>
</ul>

app/views/direct_messages/show.html.erb
<h1>Chat with <%= @chat_partner.email %></h1>

<%= form_with(model: @private_message, url: direct_message_path(chat_partner_id: @chat_partner.id), local: true) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Send" %>
  </div>
<% end %>

<h2>Messages</h2>
<ul>
  <% @private_messages.each do |message| %>
    <li>
      <strong><%= message.sender == current_user ? 'You' : @chat_partner.email %>:</strong>
      <%= message.content %>
      <small><%= message.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Chat Rooms', chat_rooms_path %></li>
    <li><%= link_to 'Direct Messages', direct_messages_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

<%= yield %>
</body>
</html>

app/views/messages/_message.html.erb
<p><%= message.user.email %>: <%= message.content %></p>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/private_messages/_private_message.html.erb
<p><%= private_message.user.email %>: <%= private_message.content %></p>

app/views/users/index.html.erb
<!--<h1>Users#index</h1>-->
<!--<p>Find me in app/views/users/index.html.erb</p>-->
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.email %> (ID: <%= user.id %>)
    </li>
  <% end %>
</ul>